-- Tạo database
USE MASTER
CREATE DATABASE SHOPEE_DB
-- Sử dụng database
USE SHOPEE_DB

-- Xóa database
USE MASTER
ALTER DATABASE SHOPEE_DB 
SET SINGLE_USER -- Đặt cơ sở dữ liệu vào chế độ SINGLE_USER
WITH ROLLBACK IMMEDIATE; 
DROP DATABASE SHOPEE_DB


-- Tạo các tables kèm NOT NULL Constraint
CREATE TABLE T01_SELLERS
(
	SellerID smallint NOT NULL,
	SellerName nvarchar(255) NOT NULL,
	SellerType nvarchar(50) NOT NULL,
)

CREATE TABLE T02_ORDERS_HISTORY
(
	OrderID smallint NOT NULL,
	SellerID smallint NOT NULL,
	InvoiceAmount decimal(12,3) NOT NULL
)

CREATE TABLE T03_ORDER_DETAILS_HISTORY
(
	OrderDetailID smallint NOT NULL,
	OrderID smallint NOT NULL,
	ProductName nvarchar(255) NOT NULL,
	ProductType nvarchar(50),
	Quantity tinyint NOT NULL,
)


-- Tạo Constraint
-- Tạo PRIMARY KEY Constraint
ALTER TABLE T01_SELLERS
ADD CONSTRAINT T01_SELLERS_PK
PRIMARY KEY (SellerID)

ALTER TABLE T02_ORDERS_HISTORY
ADD CONSTRAINT T02_ORDERS_HISTORY_PK
PRIMARY KEY (OrderID)

ALTER TABLE T03_ORDER_DETAILS_HISTORY
ADD CONSTRAINT T03_ORDER_DETAILS_HISTORY_PK
PRIMARY KEY (OrderDetailID)

-- Tạo UNIQUE KEY Constraint
ALTER TABLE T01_SELLERS
ADD CONSTRAINT T01_SELLERS_U
UNIQUE (SellerName)

-- Tạo FOREIGN KEY Constraint
ALTER TABLE T02_ORDERS_HISTORY
ADD CONSTRAINT T02_ORDERS_HISTORY_FK
FOREIGN KEY (SellerID)
REFERENCES T01_SELLERS(SellerID)

ALTER TABLE T03_ORDER_DETAILS_HISTORY
ADD CONSTRAINT T03_ORDER_DETAILS_HISTORY_FK
FOREIGN KEY (OrderID)
REFERENCES T02_ORDERS_HISTORY(OrderID)

-- Tạo CHECK Constraint
ALTER TABLE T01_SELLERS
ADD CONSTRAINT T01_SELLERS_C
CHECK (SellerType in ('Normal','Preferred Seller','Preferred Seller Plus','Mall'))

ALTER TABLE T02_ORDERS_HISTORY
ADD CONSTRAINT T02_ORDERS_HISTORY_C_2
CHECK (InvoiceAmount>0)

ALTER TABLE T03_ORDER_DETAILS_HISTORY
ADD CONSTRAINT T03_ORDER_DETAILS_HISTORY_C_2
CHECK (Quantity>0)


-- QUERY
SELECT *
FROM T01_SELLERS

SELECT *
FROM T02_ORDERS_HISTORY

SELECT *
FROM T03_ORDER_DETAILS_HISTORY